<?php

session_start();
if (!isset($_SESSION["activeUser"])) // if the user is not logged in he will be redirected to the sign up page
    header("location: /course-registration-system/login.php");

if (isset($_POST["add-section"])) {
    require_once("../functions.php");
    // input validation is done later
    // First, validate the datetime
    // $dateErr = $secNumErr = $sameSecErr = $insertErr = "";
    // unset($dateErr, $secNumErr, $sameSecErr, $insertErr);

    // $datetime = $_POST["datetime"];
    // $currentDate = date('d-m-y h:i:s');
    // // $userDate = date();
    // echo $currentDate;
    // echo $datetime;
    // if ($datetime < $currentDate) {
    //     $dateErr = "Invalid date or time!";
    //     header("location: add-section.php");
    // }

    // // Also validate the section number
    // $sectionNumber = checkInput($_POST["section-num"]);
    // if (preg_match('/^\d+$/', $sectionNumber)) {
    //     $secNumErr = "Invalid Section Number!";
    //     header("location: add-section.php");
    // }

    // // Second check if the section number exists
    // if (sectionExists()) {
    //     $secNumErr = "Section number already exists!";
    //     header("location: add-section.php");
    // }

    // Finally add the section
    $courseId = $_POST["course-code"];
    $professorId = $_POST["prof-name"];
    $sectionNum = $_POST["section-num"];
    $buildingId = $_POST["bldng"];
    $roomId = $_POST["room"];
    $dateTime = $_POST["datetime"];
    $days = $_POST["days"];
    $semId = getCurrentSemesterId();
    // need to reorder parameters
    if (addSection($semId, $courseId, $sectionNum, $professorId, $roomId, $days, $dateTime)) {
        // display the popup screen and empty the selections or screens
        $feedback = true;
    } else {
        // display error popup screen + do not empty the screen
    }

    // ...

    //     try {
    //         require("connection.php");
    //         $sql = "INSERT INTO RESERVATIONS VALUES (null, ?, ?, ?, ?, NOW())";
    //         $db->beginTransaction();
    //         $statement = $db->prepare($sql);
    //         $statement->execute(array($tripId, $_SESSION["activeUser"][0], 0, null));

    //         if ($statement->rowCount() != 1) {
    //             header("location: home.php?reserved=false");
    //         } else {
    //             header("location: home.php?reserved=true");
    //         }
    //     } catch (PDOException $e) {
    //         $db->rollBack();
    //         // header("location: home.php?reserved=notfalse");
    //         echo "Error: " . $e->getMessage();
    //     }

    //     $db = null;

    //     echo $statement->rowCount();
}



?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Section</title>

    <!-- Adding the css files -->
    <link rel="stylesheet" href="../css/reset.css">
    <link rel="stylesheet" href="../css/popup.scss">
    <link rel="stylesheet" href="../css/style.css" />

    <!-- Adding the Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
    </style>

    <!-- Adding FontAwesome Kit -->
    <script src="https://kit.fontawesome.com/163915b421.js" crossorigin="anonymous"></script>
</head>

<body>

    <?php require("../header.php");
    require_once("../functions.php");
    // Required varialbes for adding the section
    $courses = getCourses(); // get the courses list from the database
    $professorNames = getProfessorNames();
    $buildings = getBuildings();
    $rooms = getRooms();

    ?>


    <main class="payment-main" style="background-color: white; background-image: none; text-align: left;">
        <h1 class="catalogue-header" style="color: #4056A1;">Add Section</h1>

        <!-- 
            Needed Information to add a section:
                - Course Code List (offered by server)
                - Prof Name List(offered by server)
                - room List (offered by server)
                - building List DONE TILL HERE
                - section number (generated by the system; after selecting the course)
                - date and time (validation: no date from the past) :: need time validation



                Pop up message should display the seciton number to user
         -->
        <form method="post" class="form" style="margin-left: 2.75em;">
            <div class="attendance-flex catalogue-main">
                <!-- Course Code and Section Number -->
                <div class="attendance-inner-flex">
                    <label for="course-code">Course Code:</label><br><br>
                    <select class="selecter" onchange="getSection(this.value)" name="course-code" id="course-code">
                        <?php
                        if ($courses != array())
                            for ($i = 0; $i < count($courses); $i++)
                                foreach ($courses[$i] as $id => $code) {
                                    echo "<option value='" . strval($id) . "'>" . $code . "</option>";
                                }

                        ?>
                    </select>
                    <br><br>
                    <!-- Section Number -->
                    <label for="section-num">Section Number:</label><br><br>
                    <!-- Will be populated automatically by the system after selecting the course code, again by AJAX -->
                    <input type="text" class="selecter" name="section-num" id="section-num">
                </div>

                <!-- Building and Room -->
                <div class="attendance-inner-flex" style="margin-left: 2.5em;">
                    <label for="bldng">Building:</label><br><br>
                    <select onchange="getRooms(this.value)" class="selecter" name="bldng" id="bldng">
                        <option value="">Select a Building</option>
                        <?php
                        if ($buildings != array())
                            for ($i = 0; $i < count($buildings); $i++)
                                foreach ($buildings[$i] as $id => $name) {
                                    echo "<option value='" . strval($id) . "'>" . $name . "</option>";
                                }

                        ?>
                    </select>
                    <br><br><br>
                    <label for="room">Room:</label><br><br>
                    <select class="selecter" name="room" id="room">
                        <option value="">Select a Room</option>
                        <!-- The options will be optained from the database using AJAX and PHP -->
                        <!-- Refer to the script at the end of the page, after <body> -->
                    </select>
                </div>

                <!-- Professor and Date+Time -->
                <div class="attendance-inner-flex" style="margin-left: 2.5em;">
                    <label for="prof-name">Professor:</label><br><br>
                    <select class="selecter" name="prof-name" id="prof-name">
                        <?php
                        if ($professorNames != array())
                            for ($i = 0; $i < count($professorNames); $i++)
                                foreach ($professorNames[$i] as $id => $name) {
                                    echo "<option value='" . strval($id) . "'>" . $name . "</option>";
                                }

                        ?>
                    </select>
                    <br><br><br>
                    <label for="datetime">Days:</label><br><br>
                    <select class="selecter" name="days" id="days">
                        <option value="UTH">UTH</option>
                        <option value="MW">MW</option>
                    </select>
                </div>

                <div class="attendance-inner-flex" style="margin-left: 2.5em;">
                    <label for="datetime">Time:</label><br><br>
                    <input type="time" name="datetime" id="datetime">
                </div>
            </div>
            <input type="submit" class="butn primary-butn sign-butn no-margin-left margin-top small" name="add-section" id="add-section" value="Add a Section!">
        </form>

        <?php
        if (isset($feedback) and $feedback == true)
            createSuccessPopUp("Section Added Successfully!");
        if (isset($secNumErr))
            echo "<p style='color: red; font-size: 1em;'></p>$secNumErr</p>";
        if (isset($sameSecErr))
            echo "<p style='color: red; font-size: 1em;'></p>$sameSecErr</p>";
        if ((isset($insertErr)))
            echo "<p style='color: red; font-size: 1em;'></p>$insertErr</p>";
        ?>
    </main>

    <?php require("../footer.php") ?>
</body>
<!-- Script for getting the rooms after the user selects the buildings :: Using AJAX
     Author: Omar Eldanasoury
 -->
<script>
    /**@@function getRooms()
     * sends user choice to the script to get
     * rooms of the building
     * 
     * @author Omar Eldanasoury
     */
    function getRooms(buildingId) {
        if (buildingId.length == 0) {
            return;
        }

        const request = new XMLHttpRequest();
        request.onload = showRooms;
        request.open("GET", "getRooms.php?id=" + buildingId);
        request.send();
    }

    /**@function showRooms
     * populated the options inside <select>
     * after getting the rooms
     * 
     * @author Omar Eldanasoury
     */
    function showRooms() {
        clearRooms();
        results = this.responseText.split("#");
        for (let result of results) {
            idAndRoom = result.split("@");
            if (idAndRoom[0] == '')
                continue;
            document.getElementById("room").innerHTML += "\n<option value='" + idAndRoom[0] + "'>" + idAndRoom[1] + "</option>";
        }
    }

    /**@function clearRooms
     * Clears the options to
     * populate new options when
     * user's choice changes.
     * 
     * @author Omar Eldanasoury
     */
    function clearRooms() {
        document.getElementById("room").innerHTML = "<option value=''>Select a Room</option>"
    }



    // // *********************************************

    // /**@function getSection
    //  * gets the successive section number to be added
    //  * for a particular course id; using AJAX.
    //  * 
    //  * @author Omar Eldanasoury
    //  */
    // function getSection(courseId) {
    //     if (courseId.length == 0) {
    //         return;
    //     }

    //     const request = new XMLHttpRequest();
    //     request.onload = showSection;
    //     request.open("GET", "getRecentSection.php?cid=" + courseId);
    //     request.send();
    // }

    // /**@function showSection
    //  * Shows the section number
    //  * retrieved from the database
    //  * to the user through html.
    //  */
    // function showSection() {
    //     clearSectionNumber();
    //     results = this.responseText.split("#");
    //     //console.log(results);
    //     for (let result of results) {
    //         idAndRoom = result.split("@");
    //         if (idAndRoom[0] == '')
    //             continue;
    //         document.getElementById("room").innerHTML += "\n<option value='" + idAndRoom[0] + "'>" + idAndRoom[1] + "</option>";
    //     }
    // }

    // /**@function clearSectionNumber
    //  * clears the html that shows the section number
    //  */
    // function clearSectionNumber() {
    //     document.getElementById("section-number").value = "";
    // }
</script>

<!-- Script for popup -->
<script>
    document.getElementById('button').addEventListener('click', function() {
        document.querySelector('.bg-modal').style.display = 'flex';
    });

    document.querySelector('.close').addEventListener('click', function() {
        document.querySelector('.bg-modal').style.display = 'none';
    });
</script>

</html>