<?php

session_start(); // for the header
if (!isset($_SESSION["activeUser"])) // if the user is not logged in he will be redirected to the sign up page
    header("location: login.php");
if (isset($_POST["add-section"])) {
    //     try {
    //         require("connection.php");
    //         $sql = "INSERT INTO RESERVATIONS VALUES (null, ?, ?, ?, ?, NOW())";
    //         $db->beginTransaction();
    //         $statement = $db->prepare($sql);
    //         $statement->execute(array($tripId, $_SESSION["activeUser"][0], 0, null));

    //         if ($statement->rowCount() != 1) {
    //             header("location: home.php?reserved=false");
    //         } else {
    //             header("location: home.php?reserved=true");
    //         }
    //     } catch (PDOException $e) {
    //         $db->rollBack();
    //         // header("location: home.php?reserved=notfalse");
    //         echo "Error: " . $e->getMessage();
    //     }

    //     $db = null;

    //     echo $statement->rowCount();
}



?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Section</title>

    <!-- Adding the css files -->
    <link rel="stylesheet" href="../css/reset.css">
    <link rel="stylesheet" href="../css/style.css" />

    <!-- Adding the Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
    </style>

    <!-- Adding FontAwesome Kit -->
    <script src="https://kit.fontawesome.com/163915b421.js" crossorigin="anonymous"></script>
</head>

<body>

    <?php require("../header.php");
    require_once("../functions.php");
    // Required varialbes for adding the section
    $courses = getCourses(); // get the courses list from the database
    $professorNames = getProfessorNames();
    $buildings = getBuildings();
    $rooms = getRooms();

    ?>


    <main class="payment-main" style="background-color: white; background-image: none; text-align: left;">
        <h1 class="catalogue-header" style="color: #4056A1;">Add Section</h1>

        <!-- 
            Needed Information to add a section:
                - Course Code List (offered by server)
                - Prof Name List(offered by server)
                - room List (offered by server)
                - section number (generated by the system; after selecting the course)
                - building List
                - date and time (validation: no date from the past) :: need time validation



                Pop up message should display the seciton number to user
         -->
        <form method="post" class="form" style="margin-left: 2.75em;">
            <div class="attendance-flex">
                <div class="attendance-inner-flex">
                    <label for="course-code">Course Code:</label><br><br>
                    <select class="selecter" name="course-code" id="course-code">
                        <?php
                        if ($courses != array())
                            for ($i = 0; $i < count($courses); $i++)
                                foreach ($courses[$i] as $id => $code) {
                                    echo "<option value='" . strval($id) . "'>" . $code . "</option>";
                                }

                        ?>
                    </select>
                </div>

                <div class="attendance-inner-flex" style="margin-left: 2.5em;">
                    <label for="prof-name">Professor:</label><br><br>
                    <select class="selecter" name="prof-name" id="prof-name">
                        <?php
                        if ($professorNames != array())
                            for ($i = 0; $i < count($professorNames); $i++)
                                foreach ($professorNames[$i] as $id => $name) {
                                    echo "<option value='" . strval($id) . "'>" . $name . "</option>";
                                }

                        ?>
                    </select>
                </div>

                <div class="attendance-inner-flex" style="margin-left: 2.5em;">
                    <label for="prof-name">Building:</label><br><br>
                    <select class="selecter" name="bldng" id="bldng">
                        <?php
                        foreach ($buildings as $bldng)
                            echo "<option value='$bldng'>$bldng</option>";
                        ?>
                    </select>
                </div>

                <div class="attendance-inner-flex" style="margin-left: 2.5em;">
                    <label for="prof-name">Room:</label><br><br>
                    <select class="selecter" name="bldng" id="bldng">
                        <?php
                        foreach ($rooms as $room)
                            echo "<option value='$room'>$room</option>";
                        ?>
                    </select>
                </div>

            </div>

            <input type="submit" class="butn primary-butn sign-butn no-margin-left margin-top small" name="add-secton" id="add-section" value="Add a Section!">
        </form>

    </main>

    <?php require("../footer.php") ?>
</body>

</html>